import type { Unit } from "../types";
import * as G1 from "../generators/grade1";
import * as L from "../lessons/g1";
import * as M from "../lessons/g1-s2";

/** 1학년. 단원·차시 순서는 2022 개정 국정 교과서 흐름, 성취기준 코드는 docs/audit-v2 보고서의 코드 표(원문 대조는 docs/USER-TODO.md 3번) */

export const g1s1Numbers9: Unit = {
  id: "g1-s1-numbers9",
  grade: 1,
  semester: 1,
  number: 1,
  slug: "numbers9",
  title: "9까지의 수",
  standards: [
    {
      id: "count5",
      code: "[2수01-01]",
      topic: "9까지의 수",
      title: "1부터 5까지의 수",
      conceptCards: [{ title: "하나, 둘, 셋", body: "물건을 하나씩 짚으며 세면 마지막에 센 수가 모두의 수예요.", example: "●●● → 3(셋, 삼)" }],
      generators: [L.dots5, L.read5, L.pickDots5, L.toFive, L.fingers5, L.pair5],
    },
    {
      id: "count6to9",
      code: "[2수01-01]",
      topic: "9까지의 수",
      title: "6부터 9까지의 수",
      conceptCards: [{ title: "5와 몇", body: "10칸 틀의 윗줄 5칸이 차고 아랫줄에 몇 개가 더 있는지 보면 쉽게 셀 수 있어요.", example: "●●●●● ●● → 7(일곱, 칠)" }],
      generators: [L.dots9, L.read9, L.n9.toNine, L.pickDots9, L.fingers10, L.pair9],
    },
    {
      id: "ordinal",
      code: "[2수01-01]",
      topic: "수의 순서",
      title: "수로 순서 나타내기",
      conceptCards: [{ title: "몇째", body: "순서를 말할 때는 첫째, 둘째, 셋째, …라고 해요. 어느 쪽에서 세는지 꼭 확인해요.", example: "○○●○ → ●는 왼쪽에서 셋째" }],
      generators: [L.ordinalPick, L.ordinalWhich, L.ordinalWord, L.n9.lineOrder, L.frontBack],
    },
    {
      id: "order9",
      code: "[2수01-03]",
      topic: "수의 순서",
      title: "수의 순서 알아보기",
      conceptCards: [{ title: "순서대로, 거꾸로", body: "1, 2, 3, …, 9처럼 순서대로 셀 수도 있고, 9, 8, 7, …처럼 거꾸로 셀 수도 있어요." }],
      generators: [L.seq9, L.n9.countDown, L.seqRight9, L.n9.between9, L.condOrder9],
    },
    {
      id: "one-more-less",
      code: "[2수01-03]",
      topic: "수의 크기",
      title: "1만큼 더 큰 수와 1만큼 더 작은 수, 0",
      conceptCards: [
        { title: "1만큼 더 큰 수, 1만큼 더 작은 수", body: "바로 뒤의 수는 1만큼 더 큰 수, 바로 앞의 수는 1만큼 더 작은 수예요.", example: "5보다 1만큼 더 큰 수는 6" },
        { title: "0", body: "아무것도 없는 것을 0(영)이라고 해요. 1보다 1만큼 더 작은 수가 0이에요." },
      ],
      generators: [G1.numBeforeAfter, L.oneMoreDots, L.zeroCount, L.oneMoreRev, L.between9b, L.candyChain, L.reverseOne],
    },
    {
      id: "compare9",
      code: "[2수01-03]",
      topic: "수의 크기",
      title: "수의 크기 비교하기",
      conceptCards: [{ title: "크다, 작다", body: "수를 순서대로 셀 때 뒤에 나오는 수가 더 커요.", example: "7은 4보다 큽니다. 4는 7보다 작습니다." }],
      generators: [G1.numBigger9, L.bigger9, L.orderNth9, L.moreFewerWords, L.countBigger9, L.most9, L.canBe9],
    },
  ],
};

export const g1s1Solids: Unit = {
  id: "g1-s1-solids",
  grade: 1,
  semester: 1,
  number: 2,
  slug: "solids",
  title: "여러 가지 모양",
  standards: [
    {
      id: "find-solids",
      code: "[2수03-01]",
      topic: "여러 가지 모양",
      title: "여러 가지 모양 찾기",
      conceptCards: [{ title: "세 가지 모양", body: "우리 주변의 물건은 상자 모양, 둥근기둥 모양, 공 모양으로 나눌 수 있어요.", example: "주사위: 상자 모양, 음료수 캔: 둥근기둥 모양, 축구공: 공 모양" }],
      generators: [L.solidShape, L.sameShape, L.ballCount, L.oddShape, L.shapeMore, L.twoKindsCount],
    },
    {
      id: "sort-solids",
      code: "[2수03-01]",
      topic: "여러 가지 모양",
      title: "같은 모양끼리 모으기",
      conceptCards: [{ title: "같은 모양끼리", body: "물건의 모양을 하나씩 살펴보고 같은 모양끼리 모아요." }],
      generators: [L.sortCount, L.groupName, L.wrongGroup, L.sortError, L.shapeMore],
    },
    {
      id: "solid-features",
      code: "[2수03-01]",
      topic: "여러 가지 모양",
      title: "여러 가지 모양 알아보기",
      conceptCards: [
        { title: "평평한 부분", body: "평평한 부분이 있으면 쌓을 수 있어요. 상자 모양, 둥근기둥 모양" },
        { title: "둥근 부분", body: "둥근 부분이 있으면 굴러가요. 공 모양은 어느 쪽으로도, 둥근기둥 모양은 눕히면 굴러가요." },
      ],
      generators: [L.featureThing, L.featureTrue, L.rollStack, L.peekShape, L.featureError],
    },
    {
      id: "build-solids",
      code: "[2수03-01]",
      topic: "여러 가지 모양",
      title: "여러 가지 모양으로 만들기",
      conceptCards: [{ title: "모양 세기", body: "만든 모양에서 상자, 둥근기둥, 공 모양을 각각 몇 개 사용했는지 세어 보아요." }],
      generators: [L.buildCount, L.buildMost, L.buildNeed, L.buildWho, L.solidsCount],
    },
  ],
};

export const g1s1AddSub: Unit = {
  id: "g1-s1-add-sub",
  grade: 1,
  semester: 1,
  number: 3,
  slug: "add-sub",
  title: "덧셈과 뺄셈",
  standards: [
    {
      id: "gather",
      code: "[2수01-04]",
      topic: "모으기와 가르기",
      title: "9까지의 수 모으기",
      conceptCards: [{ title: "모으기", body: "두 수를 모으면 더 큰 수가 돼요.", example: "3과 4를 모으면 7" }],
      generators: [L.as9.gather9, G1.split9, L.gatherPairs, L.gatherTwoStep, L.gatherCards],
    },
    {
      id: "split9",
      code: "[2수01-04]",
      topic: "모으기와 가르기",
      title: "9까지의 수 가르기",
      conceptCards: [{ title: "가르기", body: "한 수를 두 수로 가를 수 있어요. 가르는 방법은 여러 가지예요.", example: "7은 3과 4, 2와 5, 1과 6, …으로 가를 수 있어요." }],
      generators: [L.splitDots, L.splitWays, L.splitWrong, L.as9.splitBag, L.splitShare],
    },
    {
      id: "add9",
      code: "[2수01-05] [2수01-06]",
      topic: "덧셈",
      title: "덧셈하기",
      conceptCards: [{ title: "덧셈식", body: "3 + 4 = 7은 '3 더하기 4는 7과 같습니다'라고 읽어요. 모으기로 덧셈을 할 수 있어요." }],
      generators: [G1.add9, L.addPic, L.as9.missing9, L.addStoryPick, L.cardAdd, L.sameTotal9],
    },
    {
      id: "sub9",
      code: "[2수01-05] [2수01-06]",
      topic: "뺄셈",
      title: "뺄셈하기",
      conceptCards: [{ title: "뺄셈식", body: "7 − 4 = 3은 '7 빼기 4는 3과 같습니다'라고 읽어요. 남은 것, 더 많은 것을 구할 때 뺄셈을 해요." }],
      generators: [G1.sub9, L.subPic, L.subCompare, L.subStoryPick, L.reverseSub9, L.as9.eatBuy9],
    },
    {
      id: "zero-calc",
      code: "[2수01-06]",
      topic: "뺄셈",
      title: "0이 있는 덧셈과 뺄셈, 덧셈식과 뺄셈식",
      conceptCards: [
        { title: "0을 더하거나 빼기", body: "어떤 수에 0을 더하거나 빼면 그대로예요. 같은 수를 빼면 0이에요.", example: "5 + 0 = 5, 5 − 5 = 0" },
        { title: "덧셈식과 뺄셈식", body: "3 + 4 = 7이면 7 − 4 = 3, 7 − 3 = 4예요." },
      ],
      generators: [L.zeroCalc, L.calcBiggest9, L.factFamily9, L.canBeAdd9, L.cardsDiff9],
    },
  ],
};

export const g1s1Compare: Unit = {
  id: "g1-s1-compare",
  grade: 1,
  semester: 1,
  number: 4,
  slug: "compare",
  title: "비교하기",
  standards: [
    {
      id: "length",
      code: "[2수03-06]",
      topic: "비교하기",
      title: "길이 비교하기",
      conceptCards: [{ title: "끝 맞추기", body: "한쪽 끝을 맞추고 다른 쪽 끝을 보면 어느 것이 더 긴지 알 수 있어요. '더 길다, 더 짧다'로 말해요." }],
      generators: [G1.compareLength, L.lengthEnds, L.cmp.secondLongest, L.lengthCells, L.cmp.longest, L.tallOrder],
    },
    {
      id: "weight",
      code: "[2수03-06]",
      topic: "비교하기",
      title: "무게 비교하기",
      conceptCards: [{ title: "더 무겁다, 더 가볍다", body: "손으로 들어 보거나 시소에 올려 보아요. 시소는 무거운 쪽이 아래로 내려가요." }],
      generators: [L.heaviest, L.seesawChain, L.weightMarbles, L.weightTrade, L.weightChain4],
    },
    {
      id: "area",
      code: "[2수03-06]",
      topic: "비교하기",
      title: "넓이 비교하기",
      conceptCards: [{ title: "겹쳐 보기, 칸 세기", body: "겹쳐 보았을 때 남는 쪽이 더 넓어요. 같은 크기의 칸이 더 많은 쪽이 더 넓어요." }],
      generators: [L.cmp.countCells, G1.compareArea, L.areaDiff, L.cmp.widest, L.areaJoin],
    },
    {
      id: "capacity",
      code: "[2수03-06]",
      topic: "비교하기",
      title: "담을 수 있는 양 비교하기",
      conceptCards: [{ title: "더 많다, 더 적다", body: "그릇이 클수록 많이 담을 수 있어요. 같은 그릇이면 물의 높이가 높을수록 많이 담긴 거예요." }],
      generators: [L.cupLevel, L.containerSize, L.cupCount, L.cupCompare, L.pourReverse],
    },
  ],
};

export const g1s1Numbers50: Unit = {
  id: "g1-s1-numbers50",
  grade: 1,
  semester: 1,
  number: 5,
  slug: "numbers50",
  title: "50까지의 수",
  standards: [
    {
      id: "ten",
      code: "[2수01-01] [2수01-04]",
      topic: "10과 십몇",
      title: "10 알아보기, 10 모으기와 가르기",
      conceptCards: [{ title: "10", body: "9보다 1만큼 더 큰 수를 10이라고 해요. 10은 십 또는 열이라고 읽어요.", example: "1과 9, 2와 8, 3과 7, 4와 6, 5와 5 → 10" }],
      generators: [L.tenFrame, L.readTen, L.tenSplit, L.tenPairWrong, L.tenNeed, L.tenCards],
    },
    {
      id: "teens",
      code: "[2수01-01]",
      topic: "10과 십몇",
      title: "십몇 알아보기",
      conceptCards: [{ title: "십몇", body: "10개씩 묶음 1개와 낱개 3개는 13이에요. 13은 십삼 또는 열셋이라고 읽어요." }],
      generators: [L.teenFrame, L.readTeen, L.teenSplit, L.teenMoreLess, L.teenPack, L.teenCond],
    },
    {
      id: "split19",
      code: "[2수01-04]",
      topic: "10과 십몇",
      title: "19까지의 수 모으기와 가르기",
      conceptCards: [{ title: "10을 넘는 모으기", body: "먼저 10을 만들고 남은 것을 세면 쉬워요.", example: "8과 5 → 8과 2로 10, 남은 3 → 13" }],
      generators: [L.gather19, L.split19, L.split19Wrong, L.share19, L.gather19Cards],
    },
    {
      id: "tens",
      code: "[2수01-01]",
      topic: "50까지의 수",
      title: "10개씩 묶어 세기",
      conceptCards: [{ title: "몇십", body: "10개씩 묶음 2개는 20(이십, 스물), 3개는 30(삼십, 서른), 4개는 40(사십, 마흔), 5개는 50(오십, 쉰)이에요." }],
      generators: [L.tensModel50, L.readTens50, L.tensRev50, L.tensSeq50, L.tensBoxes50, L.tensError],
    },
    {
      id: "count50",
      code: "[2수01-01]",
      topic: "50까지의 수",
      title: "50까지의 수 세기",
      conceptCards: [{ title: "몇십몇", body: "10개씩 묶음 2개와 낱개 3개는 23이에요. 이십삼 또는 스물셋이라고 읽어요.", example: "▮▮ ●●● = 23" }],
      generators: [G1.tensOnes50, L.read50, L.n50.tensSplit50, L.tensOnesOver50, L.n50.tensGive, L.cards50],
    },
    {
      id: "order50",
      code: "[2수01-03]",
      topic: "50까지의 수",
      title: "50까지 수의 순서",
      conceptCards: [{ title: "수의 순서", body: "수를 순서대로 쓰면 1씩 커져요. 두 수 사이에 있는 수를 찾을 때는 순서대로 써 보아요." }],
      generators: [L.seq50, G1.numBetween, L.seqBack50, L.between50, L.cond50],
    },
    {
      id: "compare50",
      code: "[2수01-03]",
      topic: "50까지의 수",
      title: "50까지 수의 크기 비교",
      conceptCards: [{ title: "크기 비교", body: "10개씩 묶음의 수가 많은 쪽이 커요. 같으면 낱개가 많은 쪽이 커요.", example: "32는 28보다 큽니다." }],
      generators: [L.bigger50, L.orderNth50, L.countBigger50, L.n50.mostCards, L.blank50],
    },
  ],
};

export const g1s2Numbers100: Unit = {
  id: "g1-s2-numbers100",
  grade: 1,
  semester: 2,
  number: 1,
  slug: "numbers100",
  title: "100까지의 수",
  standards: [
    {
      id: "tens60-90",
      code: "[2수01-01]",
      topic: "100까지의 수",
      title: "60, 70, 80, 90 알아보기",
      conceptCards: [{ title: "몇십", body: "10개씩 묶음 6개는 60(육십, 예순), 7개는 70(칠십, 일흔), 8개는 80(팔십, 여든), 9개는 90(구십, 아흔)이에요." }],
      generators: [M.tensModel100, M.readTens100, M.tensRev100, M.tensSeq100, M.tensBoxes100, M.tensNeed100],
    },
    {
      id: "count99",
      code: "[2수01-01]",
      topic: "100까지의 수",
      title: "99까지의 수",
      conceptCards: [{ title: "몇십몇", body: "10개씩 묶음 7개와 낱개 5개는 75예요. 칠십오 또는 일흔다섯이라고 읽어요." }],
      generators: [G1.tensOnes100, M.read99, M.nh.tensSplit100, M.tensOnesOver100, M.nh.boxesBuy, M.cards99],
    },
    {
      id: "order-100",
      code: "[2수01-03]",
      topic: "수의 순서와 크기",
      title: "수의 순서, 100 알아보기",
      conceptCards: [{ title: "100", body: "99보다 1만큼 더 큰 수는 100이에요. 백이라고 읽어요. 10개씩 묶음 10개도 100이에요." }],
      generators: [M.seq100, M.pt.countOn, M.between100, M.seqBack100, M.betweenCount100, M.cond100],
    },
    {
      id: "compare100",
      code: "[2수01-03]",
      topic: "수의 순서와 크기",
      title: "수의 크기 비교",
      conceptCards: [{ title: "크기 비교", body: "10개씩 묶음의 수부터 비교하고, 같으면 낱개의 수를 비교해요." }],
      generators: [M.bigger100, M.orderNth100, M.countBigger100, M.blank100, M.rangeWho100],
    },
    {
      id: "even-odd",
      code: "[2수01-01]",
      topic: "수의 순서와 크기",
      title: "짝수와 홀수",
      conceptCards: [{ title: "짝수와 홀수", body: "둘씩 짝을 지어 남는 것이 없으면 짝수, 하나가 남으면 홀수예요.", example: "짝수: 2, 4, 6, 8, 10 / 홀수: 1, 3, 5, 7, 9" }],
      generators: [M.pairDots, G1.evenOdd, M.evenCount, M.nh.evenBetween, M.parityCond],
    },
  ],
};

export const g1s2AddSub: Unit = {
  id: "g1-s2-add-sub",
  grade: 1,
  semester: 2,
  number: 2,
  slug: "add-sub",
  title: "덧셈과 뺄셈",
  standards: [
    {
      id: "add3",
      code: "[2수01-08]",
      topic: "덧셈과 뺄셈(1)",
      title: "세 수의 덧셈",
      conceptCards: [{ title: "세 수의 덧셈", body: "앞의 두 수를 먼저 더하고, 그 결과에 나머지 수를 더해요.", example: "2 + 3 + 4 → 5 + 4 = 9" }],
      generators: [G1.add3Nums, M.add3Missing, M.add3Biggest, M.as2.fruitThree, M.add3Cards],
    },
    {
      id: "sub3",
      code: "[2수01-08]",
      topic: "덧셈과 뺄셈(1)",
      title: "세 수의 뺄셈",
      conceptCards: [{ title: "세 수의 뺄셈", body: "앞에서부터 차례로 두 수씩 빼요.", example: "9 − 3 − 2 → 6 − 2 = 4" }],
      generators: [M.sub3, M.sub3Missing, M.sub3Wrong, M.sub3Left, M.sub3Reverse],
    },
    {
      id: "make10",
      code: "[2수01-06]",
      topic: "덧셈과 뺄셈(1)",
      title: "10이 되는 더하기",
      conceptCards: [{ title: "10이 되는 짝", body: "1과 9, 2와 8, 3과 7, 4와 6, 5와 5를 더하면 10이에요." }],
      generators: [G1.make10, M.tenFrameAdd, M.make10Pick, M.make10Chain, L.tenNeed, M.make10Story],
    },
    {
      id: "from10",
      code: "[2수01-06]",
      topic: "덧셈과 뺄셈(1)",
      title: "10에서 빼기",
      conceptCards: [{ title: "10에서 빼기", body: "10칸 틀에서 뺀 만큼 지우고 남은 칸을 세어요.", example: "10 − 3 = 7" }],
      generators: [M.from10, M.from10Missing, M.from10Story, M.from10Compare, M.wrong10],
    },
    {
      id: "ten-first",
      code: "[2수01-08]",
      topic: "덧셈과 뺄셈(1)",
      title: "10을 만들어 세 수 더하기",
      conceptCards: [{ title: "10 먼저 만들기", body: "세 수 중 합이 10이 되는 두 수를 먼저 더하면 계산이 쉬워요.", example: "4 + 6 + 5 → 10 + 5 = 15" }],
      generators: [M.tenFirst, M.tenFirstMissing, M.tenFirstPick, M.tenFirstStory, M.tenFirstCards],
    },
    {
      id: "carry",
      code: "[2수01-06]",
      topic: "덧셈과 뺄셈(2)",
      title: "(몇) + (몇) = (십몇)",
      conceptCards: [{ title: "10을 만들어 더하기", body: "8 + 5는 5를 2와 3으로 갈라 8 + 2 = 10, 10 + 3 = 13으로 계산해요.", example: "8 + 5 = 13" }],
      generators: [G1.addCarry1, M.carryFrame, M.as2.carryMissing, M.carryBiggest, M.as2.busCarry, M.wrongAdd18],
    },
    {
      id: "borrow",
      code: "[2수01-06]",
      topic: "덧셈과 뺄셈(2)",
      title: "(십몇) − (몇) = (몇)",
      conceptCards: [{ title: "10에서 빼기", body: "13 − 7은 13을 10과 3으로 갈라 10 − 7 = 3, 3 + 3 = 6으로 계산해요.", example: "13 − 7 = 6" }],
      generators: [M.borrow, G1.subBorrow1, M.borrowMissing, M.borrowReverse, M.borrowError],
    },
    {
      id: "add2",
      code: "[2수01-06]",
      topic: "덧셈과 뺄셈(3)",
      title: "두 자리 수의 덧셈",
      conceptCards: [{ title: "같은 자리끼리", body: "낱개는 낱개끼리, 10개씩 묶음은 묶음끼리 더해요.", example: "23 + 45 = 68, 30 + 20 = 50" }],
      generators: [G1.add2NoCarry, M.addTens, M.as2.twoDigitMissing, M.add2Story, M.add2Biggest, M.cardsAdd2, M.add2MoreTotal],
    },
    {
      id: "sub2",
      code: "[2수01-06]",
      topic: "덧셈과 뺄셈(3)",
      title: "두 자리 수의 뺄셈",
      conceptCards: [{ title: "같은 자리끼리", body: "낱개는 낱개끼리, 10개씩 묶음은 묶음끼리 빼요.", example: "68 − 23 = 45, 50 − 20 = 30" }],
      generators: [G1.sub2NoBorrow, M.sub2Missing, M.sub2Error, M.sub2Compare, M.wrongSub2, M.as2.stickers2],
    },
  ],
};

export const g1s2ShapesClock: Unit = {
  id: "g1-s2-shapes-clock",
  grade: 1,
  semester: 2,
  number: 3,
  slug: "shapes-clock",
  title: "모양과 시각",
  standards: [
    {
      id: "find-flat",
      code: "[2수03-03]",
      topic: "여러 가지 모양",
      title: "△, □, ○ 모양 찾기",
      conceptCards: [{ title: "세모, 네모, 동그라미", body: "물건의 테두리를 보면 △, □, ○ 모양을 찾을 수 있어요.", example: "삼각자: △, 공책: □, 동전: ○" }],
      generators: [M.flatShapeCount, M.flatObject, M.flatOdd, M.shapeMostLeast, M.flatMore, M.corners],
    },
    {
      id: "flat-features",
      code: "[2수03-03]",
      topic: "여러 가지 모양",
      title: "△, □, ○ 모양 알아보기",
      conceptCards: [{ title: "뾰족한 곳과 선", body: "△ 모양은 뾰족한 곳이 3군데, □ 모양은 4군데예요. ○ 모양은 뾰족한 곳이 없고 둥글어요." }],
      generators: [M.flatFeature, M.flatTrue, M.traceShape, M.flatGuess, M.flatError],
    },
    {
      id: "flat-make",
      code: "[2수03-03]",
      topic: "여러 가지 모양",
      title: "여러 가지 모양으로 꾸미기",
      conceptCards: [{ title: "모양 꾸미기", body: "△, □, ○ 모양으로 여러 가지 그림을 꾸밀 수 있어요. 사용한 모양을 하나씩 세어 보아요." }],
      generators: [M.flatUsed, M.flatNeed, M.flatMakeMost, M.sticks, M.flatMakeTwo],
    },
    {
      id: "oclock",
      code: "[2수03-07]",
      topic: "시각",
      title: "몇 시 알아보기",
      conceptCards: [{ title: "몇 시", body: "긴바늘이 12를 가리키면 짧은바늘이 가리키는 수가 '몇 시'예요.", example: "짧은바늘 3, 긴바늘 12 → 3시" }],
      generators: [M.clockHour, M.clockHand, M.clockPick, M.clockEarliest, M.clockWho, M.clockError],
    },
    {
      id: "half-hour",
      code: "[2수03-07]",
      topic: "시각",
      title: "몇 시 30분 알아보기",
      conceptCards: [{ title: "몇 시 30분", body: "긴바늘이 6을 가리키면 30분이에요. 짧은바늘은 두 수의 가운데에 있고, 지나온 수가 '몇 시'예요.", example: "짧은바늘 3과 4 사이, 긴바늘 6 → 3시 30분" }],
      generators: [M.clockHalf, G1.clockRead, M.halfHand, M.halfPick, M.halfOrder, M.halfError],
    },
  ],
};

export const g1s2Patterns: Unit = {
  id: "g1-s2-patterns",
  grade: 1,
  semester: 2,
  number: 4,
  slug: "patterns",
  title: "규칙 찾기",
  standards: [
    {
      id: "repeat",
      code: "[2수02-01]",
      topic: "규칙 찾기",
      title: "규칙 찾기",
      conceptCards: [{ title: "되풀이", body: "○△○△처럼 똑같이 되풀이되는 부분을 찾으면 다음 모양을 알 수 있어요." }],
      generators: [G1.patternRepeat, M.nthRepeat, M.patternUnit, M.patternCount, M.patternNth],
    },
    {
      id: "make-pattern",
      code: "[2수02-02]",
      topic: "규칙 찾기",
      title: "규칙 만들기",
      conceptCards: [{ title: "나만의 규칙", body: "두 가지 이상의 모양이나 색으로 되풀이되는 규칙을 만들 수 있어요. 가로줄과 세로줄의 규칙도 살펴보아요." }],
      generators: [M.gridPattern, M.patternWrong, M.patternFill, M.notPattern, M.shapeColor],
    },
    {
      id: "number-pattern",
      code: "[2수02-01]",
      topic: "수의 규칙",
      title: "수 배열에서 규칙 찾기",
      conceptCards: [{ title: "뛰어 세기", body: "2, 4, 6, 8처럼 일정하게 커지거나 작아지는 규칙을 찾아요." }],
      generators: [M.pt.countOn, G1.skipCount100, M.rulePick, M.pt.fifthNumber, M.ruleReverse],
    },
    {
      id: "hundred-chart",
      code: "[2수02-01]",
      topic: "수의 규칙",
      title: "수 배열표에서 규칙 찾기",
      conceptCards: [{ title: "수 배열표", body: "1부터 100까지의 수 배열표에서 오른쪽으로 한 칸 가면 1씩, 아래로 한 칸 가면 10씩 커져요." }],
      generators: [M.chartBlank, M.chartBelow, M.chartColor, M.chartCond, M.chartNth],
    },
    {
      id: "represent",
      code: "[2수02-01]",
      topic: "수의 규칙",
      title: "규칙을 여러 가지 방법으로 나타내기",
      conceptCards: [{ title: "모양을 수로", body: "○는 1, △는 2처럼 규칙을 수나 몸동작으로 바꾸어 나타낼 수 있어요.", example: "○△○△ → 1, 2, 1, 2" }],
      generators: [M.shapeToNum, M.numToShape, M.bodyPattern, M.codeSum, M.codeNth],
    },
  ],
};
